alert totp_enrollment_store "TOTP_ENROLL_TRIGGER:(.*)" {
    exec command="/config/totp/totp_enroll.sh"
}
alert totp_unenroll_store "TOTP_UNENROLL_TRIGGER:(.*)" {
    exec command="/config/totp/totp_unenroll.sh"
}